package model;

public enum FaultStatus {
    FOUND,
    FOUND_AND_FIXED,
    FOUND_AND_NOT_FIXED,
    CLAIMED_BY_CLIENT,
    CLAIMED_BY_CLIENT_AND_FIXED,
    CLAIMED_BY_CLIENT_AND_NOT_FIXED,
    CLAIMED_BY_CLIENT_AND_REFUSED_TO_FIX,
    CLAIMED_BY_CLIENT_AND_NOT_FOUND;
}
